# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticha_id', models.IntegerField(blank=True)),
                ('pages', models.CharField(blank=True, max_length=30)),
                ('type_of_document', models.CharField(blank=True, max_length=50)),
                ('type_of_document_es', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('pdf', models.CharField(blank=True, max_length=100)),
                ('call_number', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('title_es', models.CharField(blank=True, max_length=100)),
                ('archive', models.CharField(blank=True, max_length=100)),
                ('collection', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('is_translation', models.CharField(blank=True, max_length=30)),
                ('primary_parties', models.CharField(blank=True, max_length=200)),
                ('primary_parties_es', models.CharField(blank=True, max_length=200)),
                ('date_digitized', models.DateField(blank=True)),
                ('year', models.IntegerField(blank=True)),
                ('transcription', models.TextField(blank=True)),
                ('permission_link', models.CharField(blank=True, max_length=200)),
                ('has_translation', models.CharField(blank=True, max_length=30)),
                ('scribe', models.CharField(blank=True, max_length=100)),
                ('witnesses', models.CharField(blank=True, max_length=300)),
                ('witnesses_es', models.CharField(blank=True, max_length=300)),
                ('acknowledgements', models.TextField(blank=True)),
            ],
        ),
    ]
