# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='ticha_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
