# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0002_auto_20160601_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='date_digitized',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
