# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0003_auto_20160601_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='year',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
