# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0004_auto_20160601_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='primary_parties_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Personajes principales'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='ticha_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ticha ID'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='title_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='type_of_document_es',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de documentos'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='witnesses_es',
            field=models.CharField(blank=True, max_length=300, verbose_name='Testigos'),
        ),
    ]
