# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0005_auto_20160602_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='pdf',
            field=models.CharField(blank=True, max_length=100, verbose_name='PDF'),
        ),
    ]
