# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0006_auto_20160602_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
