# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0007_manuscript_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='date_digitized_es',
            field=models.DateField(blank=True, null=True),
        ),
    ]
