# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0013_auto_20160606_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticha_id', models.CharField(blank=True, max_length=30, verbose_name='Ticha ID')),
                ('pages', models.CharField(blank=True, max_length=30)),
                ('type_of_document', models.CharField(blank=True, max_length=50)),
                ('type_of_document_es', models.CharField(blank=True, max_length=50, verbose_name='Tipo de documentos')),
                ('language', models.CharField(blank=True, max_length=50)),
                ('pdf', models.CharField(blank=True, max_length=100, verbose_name='PDF')),
                ('call_number', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('title_es', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('archive', models.CharField(blank=True, max_length=100)),
                ('collection', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('is_translation', models.CharField(blank=True, max_length=30)),
                ('primary_parties', models.CharField(blank=True, max_length=200)),
                ('primary_parties_es', models.CharField(blank=True, max_length=200, verbose_name='Personajes principales')),
                ('date_digitized', models.DateField(blank=True, null=True)),
                ('date_digitized_es', models.DateField(blank=True, null=True)),
                ('year', models.CharField(blank=True, default='', max_length=10)),
                ('transcription', models.TextField(blank=True)),
                ('permission_link', models.CharField(blank=True, max_length=200)),
                ('has_translation', models.CharField(blank=True, max_length=30)),
                ('scribe', models.CharField(blank=True, max_length=100)),
                ('witnesses', models.CharField(blank=True, max_length=300)),
                ('witnesses_es', models.CharField(blank=True, max_length=300, verbose_name='Testigos')),
                ('acknowledgements', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ManuscriptNew',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='date_digitized_es',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='permission_link',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='primary_parties_es',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='ticha_id',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='town',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='type_of_document',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='type_of_document_es',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='witnesses_es',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='agradecimientos',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='archivo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='colección',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='document_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='escribano',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='fecha',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='idioma',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='material_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='número_de_etiqueta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='page',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='personajes_principales',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='pueblo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='páginas',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='testigos',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='tipo_del_documento',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='town_modern_official',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='town_short',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='título',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='acknowledgements',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='archive',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='call_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='collection',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='date_digitized',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='has_translation',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='is_translation',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='language',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='primary_parties',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='scribe',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='slug',
            field=models.SlugField(verbose_name='Ticha ID'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='transcription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='witnesses',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='year',
            field=models.CharField(default='', max_length=10),
        ),
    ]
