# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0014_auto_20160606_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='título',
            field=models.CharField(default='', max_length=100),
        ),
    ]
