# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0015_auto_20160606_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='acknowledgements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='agradecimientos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='archive',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='archivo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='call_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='colección',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='collection',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='date_digitized',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='escribano',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='fecha',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='has_translation',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='is_translation',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='material_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='número_de_etiqueta',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='page',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='personajes_principales',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='primary_parties',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='pueblo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='páginas',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='scribe',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='testigos',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='town_modern_official',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='town_short',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='transcription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='witnesses',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='year',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
