# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0016_auto_20160606_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='percent_needs_review',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='permission_file',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='requester_project',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
