# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0017_auto_20160606_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='omeka_id',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='requester_project',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Requester/Project'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='town_modern_official',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Town (Modern Official)'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='town_short',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Town (Short)'),
        ),
    ]
