# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0018_auto_20160608_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscribedManuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('html_transcript', models.FileField(blank=True, upload_to='html/')),
                ('xml_transcript', models.FileField(blank=True, upload_to='xml/')),
            ],
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='omeka_id',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Omeka ID'),
        ),
    ]
