# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0019_auto_20160608_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcribedmanuscript',
            name='html_transcript',
        ),
        migrations.AlterField(
            model_name='transcribedmanuscript',
            name='xml_transcript',
            field=models.FileField(blank=True, upload_to='xml/', verbose_name='XML Transcript'),
        ),
    ]
