# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0020_auto_20160608_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManuscriptOld',
        ),
        migrations.AddField(
            model_name='transcribedmanuscript',
            name='template_path',
            field=models.FilePathField(blank=True),
        ),
    ]
