# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0022_remove_transcribedmanuscript_template_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.TextField()),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapotexts.TranscribedManuscript')),
            ],
        ),
    ]
