# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0023_manuscriptpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscriptpage',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
