# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0024_manuscriptpage_page_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manuscriptpage',
            old_name='manuscript',
            new_name='man',
        ),
    ]
