# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0025_auto_20160609_1256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manuscript',
            new_name='Handwritten',
        ),
        migrations.RenameModel(
            old_name='ManuscriptPage',
            new_name='Page',
        ),
        migrations.RenameModel(
            old_name='TranscribedManuscript',
            new_name='Printed',
        ),
        migrations.AlterModelOptions(
            name='handwritten',
            options={'verbose_name': 'Handwritten Manuscript'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Printed Manuscript Page'},
        ),
        migrations.AlterModelOptions(
            name='printed',
            options={'verbose_name': 'Printed Manuscript'},
        ),
    ]
