# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0026_auto_20160609_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
