# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0027_auto_20160610_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printed',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='printed',
            name='xml_transcript',
            field=models.FileField(blank=True, upload_to='', verbose_name='XML Transcript'),
        ),
    ]
