# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0028_auto_20160613_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='printed',
            name='convert_to_html',
            field=models.BooleanField(default=True, verbose_name='Convert to HTML'),
        ),
    ]
