# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0029_printed_convert_to_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='printed',
            name='paginate',
            field=models.BooleanField(default=True),
        ),
    ]
