# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0031_page_linear_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='linear_page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
