# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0032_auto_20160614_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='transcription_regular',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
