# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0033_page_transcription_regular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='linear_page_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapotexts.Printed', verbose_name='Manuscript'),
        ),
        migrations.AlterField(
            model_name='page',
            name='transcription_regular',
            field=models.TextField(verbose_name='Regular Transcription'),
        ),
    ]
