# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0035_auto_20160615_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='linear_page_number',
            field=models.CharField(blank=True, default='0000', max_length=4),
        ),
    ]
