# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0036_auto_20160615_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_number',
            new_name='page_id',
        ),
        migrations.AlterField(
            model_name='printed',
            name='convert_to_html',
            field=models.BooleanField(default=True, help_text='This may take several minutes.', verbose_name='Convert to HTML'),
        ),
    ]
