# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0037_auto_20160615_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_id',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Page ID'),
        ),
    ]
