# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0038_auto_20160616_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='printed',
            name='last_page',
            field=models.CharField(default='0000', max_length=4),
            preserve_default=False,
        ),
    ]
