# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0038_auto_20160616_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pages', models.ManyToManyField(to='zapotexts.Page')),
            ],
        ),
    ]
