# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0039_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='words',
            field=models.ManyToManyField(to='zapotexts.Word'),
        ),
    ]
