# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0040_page_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='words',
        ),
    ]
