# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0042_auto_20160616_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
