# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0043_word_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='printed',
            name='extract_words',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='printed',
            name='convert_to_html',
            field=models.BooleanField(default=True, help_text='This may take                                                        several minutes.', verbose_name='Convert to HTML'),
        ),
    ]
