# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0044_auto_20160617_1057'),
        ('zapotexts', '0039_printed_last_page'),
    ]

    operations = [
    ]
