# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0045_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='linear_page_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='printed',
            name='last_page',
            field=models.IntegerField(),
        ),
    ]
