# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0046_auto_20160621_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printed',
            name='last_page',
            field=models.IntegerField(default=0),
        ),
    ]
