# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0048_auto_20160621_1447'),
    ]

    operations = [
            migrations.RenameModel('Printed', 'PrintedText'),
            migrations.RenameModel('Handwritten', 'HandwrittenText')
    ]
