# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0049_auto_20160622_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handwrittentext',
            options={'verbose_name': 'Handwritten Text'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Printed Text Page'},
        ),
        migrations.AlterModelOptions(
            name='printedtext',
            options={'verbose_name': 'Printed Text'},
        ),
        migrations.AlterField(
            model_name='page',
            name='man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapotexts.PrintedText', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='word',
            name='czi',
            field=models.IntegerField(default=0, verbose_name='Colonial Zapotec                                                        Identifier'),
        ),
    ]
