# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0050_auto_20160622_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handwrittentext',
            options={},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Printed text page'},
        ),
        migrations.AlterModelOptions(
            name='printedtext',
            options={},
        ),
        migrations.RemoveField(
            model_name='printedtext',
            name='extract_words',
        ),
        migrations.RemoveField(
            model_name='printedtext',
            name='paginate',
        ),
        migrations.AlterField(
            model_name='printedtext',
            name='convert_to_html',
            field=models.BooleanField(default=True, help_text='This may take several minutes.', verbose_name='Convert to HTML'),
        ),
        migrations.AlterField(
            model_name='word',
            name='czi',
            field=models.IntegerField(default=0, verbose_name='Colonial Zapotec Identifier'),
        ),
    ]
