# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0051_auto_20160712_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='printedtext',
            name='insert_flex_data',
            field=models.BooleanField(default=True, verbose_name='Insert FLEx data'),
        ),
    ]
