# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0052_printedtext_insert_flex_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='printedtext',
            name='extract_words',
            field=models.BooleanField(default=True, verbose_name='Extract words'),
        ),
    ]
