# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0053_printedtext_extract_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwrittentext',
            name='timeline_headline',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='handwrittentext',
            name='timeline_media_thumbnail',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='handwrittentext',
            name='timeline_start_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='handwrittentext',
            name='timeline_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
