# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0054_auto_20161017_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwrittentext',
            name='date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='handwrittentext',
            name='fecha',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='handwrittentext',
            name='has_translation',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='handwrittentext',
            name='idioma',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='handwrittentext',
            name='is_translation',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='handwrittentext',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='handwrittentext',
            name='material_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='handwrittentext',
            name='page',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='handwrittentext',
            name='percent_needs_review',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='handwrittentext',
            name='personajes_principales',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='handwrittentext',
            name='primary_parties',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='handwrittentext',
            name='páginas',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='handwrittentext',
            name='timeline_start_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='transcription_regular',
            field=models.TextField(verbose_name='Regular Transcription'),
        ),
    ]
