# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-28 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0055_auto_20161027_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwrittentext',
            name='interlinear_analysis',
            field=models.TextField(blank=True, default=''),
        ),
    ]
