# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-27 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0057_auto_20170125_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='transcription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='transcription_regular',
            field=models.TextField(blank=True, verbose_name='Regular Transcription'),
        ),
    ]
