# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-27 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0058_auto_20170127_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_to_zap', models.TextField()),
                ('zap_to_en', models.TextField()),
            ],
        ),
    ]
