# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0059_dictionary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name_plural': 'dictionaries'},
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='en_to_zap',
            field=models.TextField(verbose_name='English to Zapotec'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='zap_to_en',
            field=models.TextField(verbose_name='Zapotec to English'),
        ),
    ]
