# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-08 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0060_auto_20170127_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printedtext',
            name='convert_to_html',
        ),
        migrations.RemoveField(
            model_name='printedtext',
            name='extract_words',
        ),
        migrations.RemoveField(
            model_name='printedtext',
            name='insert_flex_data',
        ),
        migrations.AddField(
            model_name='printedtext',
            name='first_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='printedtext',
            name='flex_export',
            field=models.FileField(blank=True, upload_to='', verbose_name='FLEx Export'),
        ),
    ]
