# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0061_auto_20170208_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printedtext',
            name='first_page',
            field=models.IntegerField(default=0, verbose_name='First page of transcript'),
        ),
        migrations.AlterField(
            model_name='printedtext',
            name='flex_export',
            field=models.FileField(blank=True, upload_to='', verbose_name='FLEx export'),
        ),
        migrations.AlterField(
            model_name='printedtext',
            name='last_page',
            field=models.IntegerField(default=0, verbose_name='Last page of manuscript'),
        ),
        migrations.AlterField(
            model_name='printedtext',
            name='xml_transcript',
            field=models.FileField(blank=True, upload_to='', verbose_name='XML transcript'),
        ),
    ]
