# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-27 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0063_auto_20170227_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='printedtext',
            name='citation',
            field=models.TextField(blank=True),
        ),
    ]
