# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0064_printedtext_citation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printedtext',
            name='xml_transcript',
        ),
        migrations.AddField(
            model_name='printedtext',
            name='html_file',
            field=models.FileField(blank=True, upload_to='', verbose_name='HTML transcript'),
        ),
    ]
