# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0065_auto_20170313_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printedtext',
            name='html_file',
        ),
        migrations.AddField(
            model_name='printedtext',
            name='html',
            field=models.TextField(blank=True, verbose_name='HTML'),
        ),
    ]
