# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-21 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0066_auto_20170313_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='workshop_notes',
            field=models.TextField(blank=True, verbose_name='Workshop Notes'),
        ),
    ]
