# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-02 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0067_page_workshop_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='czi',
            field=models.CharField(default='', max_length=10, verbose_name='Colonial Zapotec Identifier'),
        ),
    ]
