# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-02 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0068_auto_20170602_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CZWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField()),
                ('czi', models.CharField(default='', max_length=10, verbose_name='Colonial Zapotec Identifier')),
            ],
        ),
    ]
