# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-02 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0069_czword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='czword',
            options={'verbose_name': 'Colonial Zapotec word'},
        ),
    ]
