# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-12 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0070_auto_20170602_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printedtext',
            name='html',
            field=models.FileField(blank=True, upload_to='', verbose_name='XML transcription'),
        ),
    ]
