# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-12 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0071_auto_20170612_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printedtext',
            old_name='html',
            new_name='xml_transcript',
        ),
    ]
