# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-13 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0072_auto_20170612_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='pages',
        ),
        migrations.AlterModelOptions(
            name='czword',
            options={'verbose_name': 'Zapotec word'},
        ),
        migrations.AlterField(
            model_name='czword',
            name='czi',
            field=models.CharField(default='', max_length=10, verbose_name='Central Zapotec Identifier'),
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
