# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-15 20:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0073_auto_20170613_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 15, 20, 19, 20, 607100, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
