# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-16 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0074_dictionary_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
