# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-26 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0075_auto_20170616_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printedtext',
            name='first_page',
        ),
        migrations.AlterField(
            model_name='printedtext',
            name='last_page',
            field=models.IntegerField(default=0),
        ),
    ]
