# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-03 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0076_auto_20170626_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('contents', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapotexts.Dictionary')),
            ],
        ),
    ]
