# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-10 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0078_auto_20170703_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionarypage',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
        migrations.DeleteModel(
            name='DictionaryPage',
        ),
    ]
