# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-12 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0079_auto_20170710_1048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HandwrittenText',
        ),
    ]
