# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-25 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0080_delete_handwrittentext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CZWord',
        ),
    ]
