# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-21 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapotexts', '0082_printedtext_zoomable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printedtext',
            name='flex_export',
        ),
        migrations.RemoveField(
            model_name='printedtext',
            name='xml_transcript',
        ),
    ]
