# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-12 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandwrittenText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('título', models.CharField(default='', max_length=100)),
                ('language', models.CharField(default='', max_length=50)),
                ('idioma', models.CharField(default='', max_length=50)),
                ('document_type', models.CharField(default='', max_length=50)),
                ('tipo_del_documento', models.CharField(default='', max_length=50)),
                ('material_type', models.CharField(blank=True, default='', max_length=50)),
                ('archive', models.CharField(blank=True, default='', max_length=100)),
                ('archivo', models.CharField(blank=True, default='', max_length=100)),
                ('collection', models.CharField(blank=True, default='', max_length=100)),
                ('colección', models.CharField(blank=True, default='', max_length=100)),
                ('call_number', models.CharField(blank=True, default='', max_length=100)),
                ('número_de_etiqueta', models.CharField(blank=True, default='', max_length=100)),
                ('page', models.CharField(blank=True, default='', max_length=50)),
                ('páginas', models.CharField(blank=True, default='', max_length=50)),
                ('date_digitized', models.DateField(blank=True, null=True)),
                ('year', models.CharField(blank=True, default='', max_length=10)),
                ('town_modern_official', models.CharField(blank=True, default='', max_length=100, verbose_name='Town (Modern Official)')),
                ('pueblo', models.CharField(blank=True, default='', max_length=100)),
                ('primary_parties', models.CharField(blank=True, default='', max_length=300)),
                ('personajes_principales', models.CharField(blank=True, default='', max_length=300)),
                ('slug', models.SlugField(verbose_name='Ticha ID')),
                ('town_short', models.CharField(blank=True, default='', max_length=50, verbose_name='Town (Short)')),
                ('date', models.CharField(blank=True, default='', max_length=50)),
                ('fecha', models.CharField(blank=True, default='', max_length=50)),
                ('has_translation', models.CharField(blank=True, default='', max_length=50)),
                ('transcription', models.TextField(blank=True)),
                ('scribe', models.CharField(blank=True, default='', max_length=100)),
                ('escribano', models.CharField(blank=True, default='', max_length=100)),
                ('is_translation', models.CharField(blank=True, default='', max_length=50)),
                ('witnesses', models.CharField(blank=True, default='', max_length=300)),
                ('testigos', models.CharField(blank=True, default='', max_length=300)),
                ('acknowledgements', models.TextField(blank=True, default='')),
                ('agradecimientos', models.TextField(blank=True, default='')),
                ('permission_file', models.URLField(blank=True, default='')),
                ('percent_needs_review', models.CharField(blank=True, default='', max_length=50)),
                ('requester_project', models.CharField(blank=True, default='', max_length=50, verbose_name='Requester/Project')),
                ('omeka_id', models.CharField(blank=True, default='', max_length=10, verbose_name='Omeka ID')),
                ('timeline_media_thumbnail', models.CharField(blank=True, default='', max_length=100)),
                ('timeline_text', models.TextField(blank=True, default='')),
                ('timeline_headline', models.CharField(blank=True, default='', max_length=50)),
                ('timeline_start_date', models.CharField(blank=True, default='', max_length=50)),
                ('interlinear_analysis', models.TextField(blank=True, default='')),
                ('timeline_spanish_text', models.TextField(blank=True, default='')),
                ('timeline_spanish_headline', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
