# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-10 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=2)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PageIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_to_zap', models.TextField(verbose_name='English to Zapotec')),
                ('zap_to_en', models.TextField(verbose_name='Zapotec to English')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'dictionaries',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.PageIndex'),
        ),
    ]
