# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-10 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageindex',
            name='en_to_zap',
        ),
        migrations.RemoveField(
            model_name='pageindex',
            name='zap_to_en',
        ),
        migrations.AddField(
            model_name='pageindex',
            name='contents',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageindex',
            name='reverse_index',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
