# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-24 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_auto_20170710_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('html_id', models.CharField(max_length=50)),
            ],
        ),
    ]
